# 6CS012 – Artificial Intelligence and Machine Learning
# Worksheet 0 – Review on Python and NumPy for Deep Learning

**Name:Dipesh Mahato Tharu**

**Student ID:2408059**

**Module Leader: Siman Giri**

**Tutor:Bijaya Ghimire**

Date:

# **4.1 Exercise on Functions**

# **Task 1 – Unit Conversion Program**
**Question:**

Create a Python program that converts between different units of measurement.

* The program should:

  1. Prompt the user to choose the type of conversion.
  2. Ask the user to input the value to be converted.
  3. Perform the conversion and display the result.
  4. Handle potential errors such as invalid input.
  5. Use functions and include proper docstrings.

* Requirements:
  1. Functions: Define at least one function to perform the conversion.
  2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
  3. User Input: Prompt the user to select the conversion type and input the value.
  4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
  return value
* Conversion Options:
    1. Length:

      – Convert meters (m) to feet (ft).

      – Convert feet (ft) to meters (m).

    2. Weight:

      – Convert kilograms (kg) to pounds (lbs).

      – Convert pounds (lbs) to kilograms (kg).

    3. Volume:

      – Convert liters (L) to gallons (gal).

      – Convert gallons (gal) to liters (L).

In [1]:
def unit_converter(conversion_type, value):
    """
    Converts units between length, weight, and volume.

    Parameters:
    conversion_type (str): Type of conversion
    value (float): Value to convert

    Returns:
    float: Converted value
    """
    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "L_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_L":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type.")

try:
    print("Available conversions:")
    print("m_to_ft, ft_to_m, kg_to_lbs, lbs_to_kg, L_to_gal, gal_to_L")

    choice = input("Enter conversion type: ")
    value = float(input("Enter value: "))

    result = unit_converter(choice, value)
    print("Converted value:", result)

except ValueError as e:
    print("Error:", e)

Available conversions:
m_to_ft, ft_to_m, kg_to_lbs, lbs_to_kg, L_to_gal, gal_to_L
Enter conversion type: m_to_gt
Enter value: 67
Error: Unsupported conversion type.


# Task 2 – Mathematical Operations on a List
Question:

**Create a program that:**

1. Prompts the user to choose an operation (sum, average, maximum, minimum).

2. Accepts a list of numbers.

3. Performs the selected operation.

4. Handles invalid input using try-except.

5. Uses separate functions with docstrings.

In [2]:
def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers) / len(numbers)

def calculate_max(numbers):
    """Returns the maximum number."""
    return max(numbers)

def calculate_min(numbers):
    """Returns the minimum number."""
    return min(numbers)

try:
    operation = input("Choose operation (sum, avg, max, min): ")
    numbers = list(map(float, input("Enter numbers separated by space: ").split()))

    if not numbers:
        raise ValueError("List cannot be empty")

    if operation == "sum":
        print("Result:", calculate_sum(numbers))
    elif operation == "avg":
        print("Result:", calculate_average(numbers))
    elif operation == "max":
        print("Result:", calculate_max(numbers))
    elif operation == "min":
        print("Result:", calculate_min(numbers))
    else:
        print("Invalid operation")

except ValueError as e:
    print("Error:", e)

Choose operation (sum, avg, max, min): sum
Enter numbers separated by space: 6 7 8 9
Result: 30.0


# Section 4.2 – List Manipulation

**Question 1 – Extract Every Other Element**

In [3]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


**Question 2 – Slice a Sublist**

In [4]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6], 2, 4))

[3, 4, 5]


**Question 3 – Reverse a List**

In [5]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


**Question 4 – Remove First and Last Elements**

In [6]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


**Question 5 – Get First n Elements**

In [7]:
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1,2,3,4,5], 3))

[1, 2, 3]


**Question 6 – Get Last n Elements**

In [8]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1,2,3,4,5], 2))

[4, 5]


**Question 7 – Reverse Skip**

In [9]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


# Section 4.3 – Nested List Exercises

**Flatten Nested List**

In [10]:
def flatten(lst):
    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.extend(flatten(item))
        else:
            flat.append(item)
    return flat

print(flatten([[1,2],[3,[4,5]],6]))

[1, 2, 3, 4, 5, 6]


**Access Nested Element**

In [11]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


**Sum Nested List**


In [12]:
def sum_nested(lst):
    return sum(flatten(lst))

print(sum_nested([[1,2],[3,[4,5]],6]))

21


**Remove Element from Nested List**

In [13]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


**Find Max in Nested List**

In [14]:
def find_max(lst):
    return max(flatten(lst))

print(find_max([[1,2],[3,[4,5]],6]))

6


**Count Occurrences**

In [15]:
def count_occurrences(lst, elem):
    return flatten(lst).count(elem)

print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


**Deep Flatten**

In [16]:
def deep_flatten(lst):
    return flatten(lst)

**Average Nested**

In [17]:
def average_nested(lst):
    flat = flatten(lst)
    return sum(flat)/len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


## Section 10.1 – NumPy

In [18]:
import numpy as np

### **Problem 1 – Array Creation**

In [19]:
np.empty((2,2))
np.ones((4,2))
np.full((3,3),7)

arr = np.array([[1,2],[3,4]])
np.zeros_like(arr)
np.ones_like(arr)

new_list=[1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

### **Problem 2 – Array Manipulation**

###**Question 1– Create array from 10 to 49**

In [20]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###**Question 2 – Create 3x3 matrix from 0 to 8**

  

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

###**Question 3 – Create 3x3 Identity Matrix**

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###**Question 4 – Random array of size 30 and find mean**

In [23]:
rand_arr = np.random.random(30)
print("Array:", rand_arr)
print("Mean:", rand_arr.mean())

Array: [0.89599999 0.52511305 0.01753186 0.6993743  0.77881052 0.58903344
 0.2287705  0.05392885 0.41545522 0.39034326 0.23658702 0.52982078
 0.23330833 0.73559352 0.5488521  0.41087065 0.3627229  0.72683503
 0.30855231 0.34116858 0.45078599 0.30679511 0.87192355 0.95938867
 0.7306911  0.95120496 0.67471242 0.83688308 0.87081848 0.33980121]
Mean: 0.5340558921128766


###**Question 5 - 10x10 random array and find min & max**

In [24]:
arr = np.random.random((10,10))
print("Min:", arr.min())
print("Max:", arr.max())

Min: 0.015453238443530415
Max: 0.948181550790055


###**Question 6 - Replace 5th element with 1**



In [25]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
zero_arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###**Question 7 - Reverse array**



In [26]:
arr = np.array([1,2,0,0,4,0])
arr[::-1]

array([0, 4, 0, 0, 2, 1])

###**Question 8 -  2D array with 1 on border, 0 inside**



In [27]:
arr = np.zeros((5,5))
arr[0,:] = 1
arr[-1,:] = 1
arr[:,0] = 1
arr[:,-1] = 1
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Question 9 - 8x8 Checkerboard Pattern**



In [28]:
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
checker

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### Problem 3 – Array Operations

In [29]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

###**1. Add the two array**

In [30]:
x + y

array([[ 6,  8],
       [10, 13]])

###**2. Subtract the two array.**

In [31]:
x - y

array([[-4, -4],
       [-4, -3]])

###**3. Multiply the array with any integers of your choice.**


In [32]:
x * 2

array([[ 2,  4],
       [ 6, 10]])

###**4. Find the square of each element of the array.**


In [33]:
np.square(x)

array([[ 1,  4],
       [ 9, 25]])

###**5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.**


In [34]:
np.dot(v, w)        # v and w
np.dot(x, v)        # x and v
np.dot(x, y)        # x and y

array([[19, 22],
       [50, 58]])

###**6. Concatenate x(and)y along row and Concatenate v(and)w along column.**

**{Hint:try np.concatenate() or np.vstack() functions.**



In [35]:
# Concatenate x and y along rows
np.concatenate((x, y), axis=0)

# Concatenate v and w along columns
np.column_stack((v, w))

array([[ 9, 11],
       [10, 12]])

##**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?**

In [36]:
try:
    np.concatenate((x, v), axis=0)
except Exception as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


The error occurs because x is a 2D array (2x2) and v is a 1D array (2,). NumPy cannot concatenate arrays with different dimensions unless reshaped.

### **Problem 4 – Matrix Operations**

In [37]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

##**Prove following with Numpy:**

###**1. Prove A · A⁻¹ = I**

In [38]:
A_inv = np.linalg.inv(A)
np.dot(A, A_inv)

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

###**2. Prove AB ≠ BA**

In [39]:
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


###**3. Prove (AB)ᵀ = Bᵀ Aᵀ**

In [40]:
left = np.dot(A,B).T
right = np.dot(B.T, A.T)

print("Left Side:\n", left)
print("Right Side:\n", right)

Left Side:
 [[23 51]
 [13 29]]
Right Side:
 [[23 51]
 [13 29]]


##**Solve Linear Equation System**

**Given:**

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [41]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

X = np.linalg.solve(A,B)
print("Solution [x,y,z]:", X)

Solution [x,y,z]: [ 2.  1. -2.]


## **Section 10.2 – Experiment: How Fast is NumPy?**

**Objective**

**In this section, we compare the performance of Python lists and NumPy array for:**



1.   Element-wise Addition
2.   Element-wise Multiplication
3.   Dot Product
4.   Matrix Multiplication




In [42]:
import numpy as np
import time

### **Element-wise Addition**

**Using Python Lists**
perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [43]:
size = 10**6

a = list(range(size))
b = list(range(size))

start = time.time()
result = [a[i] + b[i] for i in range(size)]
end = time.time()

print("Python List Addition Time:", end - start)

Python List Addition Time: 0.07596921920776367


**Using NumPy Arrays**
Repeat the calculation and measure and print the time taken for
this operation.


In [44]:
a_np = np.arange(size)
b_np = np.arange(size)

start = time.time()
result_np = a_np + b_np
end = time.time()

print("NumPy Addition Time:", end - start)

NumPy Addition Time: 0.0027649402618408203


### **Element-wise Multiplication**

**Using Python Lists**, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

In [45]:
start = time.time()
result = [a[i] * b[i] for i in range(size)]
end = time.time()

print("Python List Multiplication Time:", end - start)

Python List Multiplication Time: 0.10078835487365723


**Using NumPy Arrays**, Repeat the calculation and measure and print the time taken for
this operation.

In [46]:
start = time.time()
result_np = a_np * b_np
end = time.time()

print("NumPy Multiplication Time:", end - start)

NumPy Multiplication Time: 0.004402875900268555


### **Dot Product**

**Using Python Lists**, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [47]:
start = time.time()
dot_product = sum(a[i] * b[i] for i in range(size))
end = time.time()

print("Python List Dot Product Time:", end - start)

Python List Dot Product Time: 0.07403731346130371


**Using NumPy Arrays**,Repeat the calculation and measure and print the time taken for
this operation.


In [48]:
start = time.time()
dot_product_np = np.dot(a_np, b_np)
end = time.time()

print("NumPy Dot Product Time:", end - start)

NumPy Dot Product Time: 0.0019001960754394531


###  **Matrix Multiplication**

 **Using Python lists** ,perform matrix multiplication of two matrices of size 1000x1000. Meesure and print the time taken for this operation.


In [49]:
import random

size_matrix = 200   # safer for Python loop version

A = [[random.random() for _ in range(size_matrix)] for _ in range(size_matrix)]
B = [[random.random() for _ in range(size_matrix)] for _ in range(size_matrix)]

start = time.time()
result = [[sum(A[i][k] * B[k][j] for k in range(size_matrix))
           for j in range(size_matrix)]
          for i in range(size_matrix)]
end = time.time()

print("Python List Matrix Multiplication Time:", end - start)

Python List Matrix Multiplication Time: 0.7377212047576904


**Using NumPy Arrays** perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [50]:
size_matrix = 1000

A_np = np.random.rand(size_matrix, size_matrix)
B_np = np.random.rand(size_matrix, size_matrix)

start = time.time()
result_np = np.dot(A_np, B_np)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

NumPy Matrix Multiplication Time: 0.04707503318786621
